updaetd for slate-ax

diff --git a/bootstrap/airgap_images/pull_carbide_rancher b/bootstrap/airgap_images/pull_carbide_rancher
--- a/bootstrap/airgap_images/pull_carbide_rancher
+++ b/bootstrap/airgap_images/pull_carbide_rancher
@@ -4,11 +4,6 @@ SOURCE_REGISTRY=rgcrprod.azurecr.us
 SOURCE_REGISTRY_USER=$1
 SOURCE_REGISTRY_PASS=$2
 
-if [ $(uname) == "Darwin" ]; then
-    MD5_BINARY="md5 -r"
-else
-    MD5_BINARY="md5sum"
-fi
 
 # Working directories & TAR
 DEST_DIRECTORY=/tmp/cert-manager-images
@@ -42,12 +37,12 @@ for image in $(helm template jetstack/cert-manager --version $CERT_MANAGER_RELEA
     dest_image=$(echo $image | sed "s/quay.io/TARGET_REGISTRY/g")
     
     # Create manifest to use during load
-    img_id_num=$(echo $RANDOM | $MD5_BINARY | head -c 20)
+    img_dir=$(mktemp -d $DEST_DIRECTORY/cert-image.XXXXXXX)
+    img_id_num=${img_dir: -18}
     echo "$img_id_num|$dest_image" >> $DEST_DIRECTORY/manifest.txt
     
     # Save image locally
-    mkdir $DEST_DIRECTORY/$img_id_num
-    cosign save --dir "$DEST_DIRECTORY/$img_id_num" $source_image
+    cosign save --dir "$img_dir" $source_image
 done
 
 # Compress directory
@@ -84,12 +79,15 @@ for image in $RANCHER_IMAGES; do
     dest_image="TARGET_REGISTRY/$image"
     
     # Create manifest to use during load
-    img_id_num=$(echo $RANDOM | $MD5_BINARY | head -c 20)
+    img_dir=$(mktemp -d $DEST_DIRECTORY/rancher-image.XXXXXXX)
+    img_id_num=${img_dir: -21}
     echo "$img_id_num|$dest_image" >> $DEST_DIRECTORY/manifest.txt
     
     # Save image locally
-    mkdir $DEST_DIRECTORY/$img_id_num
-    cosign save --dir "$DEST_DIRECTORY/$img_id_num" $source_image
+    cosign save --dir "$img_dir" $source_image
+    if [ $? != 0 ]; then
+        printf "FAILED: cosign save --dir $img_dir $source_image"
+    fi
 done
 
 # Compress directory
