added fluentbit

diff --git a/bootstrap/airgap_images/pull_misc b/bootstrap/airgap_images/pull_misc
--- a/bootstrap/airgap_images/pull_misc
+++ b/bootstrap/airgap_images/pull_misc
@@ -133,3 +133,48 @@ tar zcf "$DEST_TAR" -C "$DEST_DIRECTORY" .
 
 # Clean up working directory
 rm -rf $DEST_DIRECTORY
+
+## fluentbit
+DEST_DIRECTORY=/tmp/fluentbit-images
+DEST_TAR=/tmp/fluentbit-images.tar.gz 
+
+FLUENTBIT_RELEASE=0.20.9
+
+if [[ -d "$DEST_DIRECTORY" ]]; then
+    echo "ERROR: Directory '$DEST_DIRECTORY' exists."
+    echo "Change or delete it before running."
+    exit 1
+fi
+
+if [[ -d "$DEST_TAR" ]]; then
+    echo "ERROR: Directory '$DEST_TAR' exists."
+    echo "Change or delete it before running."
+    exit 1
+fi
+mkdir -p "$DEST_DIRECTORY"
+
+# Add harbor repo
+helm repo add fluent https://fluent.github.io/helm-charts
+helm repo update 
+
+# Grab the list of images and download them (requires docker, grep, sed, and awk)
+for image in $(helm template fluent/fluent-bit --version ${FLUENTBIT_RELEASE} | grep 'image:' | sed -e 's/^[ \t]*//' | sed 's/"//g' | sort --unique | awk '{ print $2 }'); do
+    source_image=$image
+    dest_image=$(echo $image | sed "s|busybox|TARGET_REGISTRY/fluent/busybox|g")
+    dest_image=$(echo $dest_image | sed "s|cr.fluentbit.io|TARGET_REGISTRY|g")
+
+    # Create manifest to use during load
+    img_dir=$(mktemp -d $DEST_DIRECTORY/fluentbit-image.XXXXXXX)
+    img_id_num=${img_dir: -23}
+    echo "$img_id_num|$dest_image" >> $DEST_DIRECTORY/manifest.txt
+
+    # Save image locally
+    printf "Exporting $source_image\n"
+    cosign save --dir "$img_dir" $source_image
+done
+
+# Compress directory
+tar zcf "$DEST_TAR" -C "$DEST_DIRECTORY" .
+
+# Clean up working directory
+rm -rf $DEST_DIRECTORY
